name: Docker Compose CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - uses: docker/setup-compose-action@v1
    - name: Check compose config
      run: docker compose -f docker-compose.yml config -q
    - name: Test compose file
      run: |
        docker compose pull -q
        docker compose build -q
        docker compose up -d
        sleep 10
        if docker compose ps --all --filter status=exited 2>/dev/null | greq -q "Exit"; then echo "Error: Not all containers are running" >&2; docker compose ps --all; docker compose down; exit 1; else echo "All containers are running."; fi
        docker compose down



