name: Deploy to Helios

on:
  workflow_run:
    workflows: [Docker Compose CI]
    types: [completed]

jobs:
  on-success:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
      - name: Build project
        run: |
          chmod +x ./gradlew
          ./gradlew build
      - name: Push to Helios
        env:
          SSH_HOST: ${{ secrets.SSH_HOST }}
          SSH_PORT: ${{ secrets.SSH_PORT }}
        run: |
          ssh-keyscan -p $SSH_PORT $SSH_HOST >> ~/.ssh/known_hosts
          scp -P $SSH_PORT httpd-helios.conf $SSH_HOST:~/httpd-root/conf/httpd.conf
          scp -P $SSH_PORT build/libs/labwork1.jar $SSH_HOST:~/httpd-root/fcgi-bin/app.jar
          scp -P $SSH_PORT -r src/main/resources/static/* $SSH_HOST:~/.www/
          ssh -p $SSH_PORT $SSH_HOST << 'EOF'
            pkill java
            pkill httpd
            httpd -f ~/httpd-root/conf/httpd.conf -k start
            nohup java -DFCGI_PORT=8087 -jar ~/httpd-root/fcgi-bin/app.jar
          EOF

