name: Deploy to Helios

on:
  workflow_run:
    workflows: [Docker Compose CI]
    types: [completed]

jobs:
  on-success:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
      - name: Add SSH host key to known_hosts
        env:
          SSH_PORT: ${{ secrets.SSH_PORT }}
          SSH_IP: ${{ secrets.SSH_IP }}
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan -p $SSH_PORT $SSH_IP >> ~/.ssh/known_hosts
      - name: Build project
        run: |
          chmod +x ./gradlew
          ./gradlew build
      - name: Push to Helios
        env:
          SSH_HOST: ${{ secrets.SSH_HOST }}
          SSH_PORT: ${{ secrets.SSH_PORT }}
        run: |
          scp -P $SSH_PORT httpd-helios.conf $SSH_HOST:~/httpd-root/conf/httpd.conf
          scp -P $SSH_PORT build/libs/labwork1.jar $SSH_HOST:~/httpd-root/fcgi-bin/app.jar
          scp -P $SSH_PORT -r src/main/resources/static/* $SSH_HOST:~/.www/
          ssh -p $SSH_PORT $SSH_HOST << 'EOF'
            set -e
            mkdir -p ~/httpd-root/fcgi-bin ~/httpd-root/conf ~/.www ~/run ~/logs
            if [ -f ~/run/app.pid ] && kill -0 $(cat ~/run/app.pid) 2>/dev/null; then
              kill $(cat ~/run/app.pid) || true
              sleep 1
            fi
            pkill -u "$USER" httpd || true
            httpd -f ~/httpd-root/conf/httpd.conf -k start
            daemon -r -f -p ~/run/app.pid -o ~/logs/app.log \
              java -DFCGI_PORT=8087 -XX:MaxHeapSize=1G -XX:MaxMetaspaceSize=128m \
              -jar ~/httpd-root/fcgi-bin/app.jar
          EOF

